name = "newdigitalemporium"
compatibility_date = "2025-07-03"
pages_build_output_dir = "out"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
dir = "out"
main = "./index.js"

